export enum ToolNames {
  CREATE_TIMEWEB_APP = "create_timeweb_app",
  GET_ALLOWED_PRESETS = "get_allowed_presets",
  ADD_VCS_PROVIDER = "add_vcs_provider",
  GET_VCS_PROVIDERS = "get_vcs_providers",
  GET_VCS_PROVIDER_REPOSITORIES = "get_vcs_provider_repositories",
  GET_VCS_PROVIDER_BY_REPOSITORY_URL = "get_vcs_provider_by_repository_url",
  GET_DEPLOY_SETTINGS = "get_deploy_settings",
  CREATE_FLOATING_IP = "create_floating_ip",
  CREATE_VPC = "create_vpc",
  GET_VPCS = "get_vpcs",
  CREATE_DATABASE = "create_database",
  GET_DATABASE_PRESETS = "get_database_presets",
  LIST_SERVERS = "list_servers",
  GET_SERVER = "get_server",
  START_SERVER = "start_server",
  SHUTDOWN_SERVER = "shutdown_server",
  REBOOT_SERVER = "reboot_server",
  GET_SERVER_LOGS = "get_server_logs",
  LIST_SERVER_DISK_BACKUPS = "list_server_disk_backups",
  CREATE_SERVER_DISK_BACKUP = "create_server_disk_backup",
  DELETE_SERVER_DISK_BACKUP = "delete_server_disk_backup",
  GET_ACCOUNT_FINANCES = "get_account_finances",
  GET_ACCOUNT_STATUS = "get_account_status",
}
